### ISSUE TITLE
Quick swipe gesture causes tabBar indicator to jump

### ISSUE THREAD

**Issue by BlueDevil2k6** [satya164/react-native-tab-view#1282]
### Current behavior

When quick swipe, the indicator jumps. This seems to be something that was introduced recently. The demo snack doesn't show this behavior:
https://snack.expo.dev/@satya164/react-native-tab-view-quick-start

My snack with updated libraries that is recommended by Expo SDK 42:
https://snack.expo.dev/@bluedevil2k6/rn-tab-view-issue

Uploading RPReplay_Final1634627621.mov…

### Expected behavior

Indicator doesn't bounce/jump after swipe gesture.

### Reproduction

https://snack.expo.dev/@bluedevil2k6/rn-tab-view-issue

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view          | ^3.1.1       |
| react-native-pager-view      | ^5.4.7         |
| react-native                          | 0.63.4 |
| expo                                      |  42.0.4 |
| node                                  | 16|
| npm or yarn                      |  yarn    |

**Comment by Thejeshwar-Reddy** [comment]
I am facing the same issue

**Comment by BlueDevil2k6** [comment]
I'm still dealing with this as well. Please post if you find a solution. Thank you!

**Comment by Thejeshwar-Reddy** [comment]
Hi it was fixed when i updated the package basically it updated react-native-pager-view and it got fixed

**Comment by BlueDevil2k6** [comment]
Would you mind sharing what your environment looks like (packages/versions)? I just updated to the latest react-native-pager-view and the issue still reproduces.

**Comment by hamam99** [comment]
I am facing same issue and fix the bug by updating library react-native-pager-view from 5.4.1 to 5.4.9

**Comment by BlueDevil2k6** [comment]
I updated to 5.4.9 but it still reproduces for me.

**Comment by BlueDevil2k6** [comment]
I figured out the issue, at least for me. My custom TabBar was inside the component, and thus getting re-rendered on the swipe. Not sure why the demo is bouncing, but this is no longer an issue for me.
