### ISSUE TITLE
Initial render of first tab creates weird white bar at the bottom

### ISSUE THREAD

**Issue by KrisLau** [satya164/react-native-tab-view#1342]
### Current behavior

So when I first enter a screen that has a tab view, there is a weird white bar at the bottom of the tab screen. Refer to this photo:
![image](https://user-images.githubusercontent.com/46275463/166812301-062ade07-9c87-45d4-84c4-c7764374f4ff.png)

However after I click to a different tab and click back to the first tab, the bar disappears:
![image](https://user-images.githubusercontent.com/46275463/166812576-6f8edd2a-ad5a-444c-bcae-c47b36479f63.png)

This issue only appeared after updating my `react` and `react-native` packages. Couldn't recreate in Snack but I linked one anyway. Also, there is no padding or margin set in the tab and I've tried removing the stylings on the tab view and this issue happens across the whole app on all of the tab views.

### Expected behavior

It should look like this all the time:
![image](https://user-images.githubusercontent.com/46275463/166812576-6f8edd2a-ad5a-444c-bcae-c47b36479f63.png)

### Reproduction

https://snack.expo.dev/@kris_lau/ac8f82

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.15
| react-native                           | 0.68.1
| expo                                   | N/A
| node                                   | 16.15.0
| ~npm or~ yarn                            | 1.22.18

**Comment by pedroferreira1** [comment]
I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`.

**Comment by dukemai** [comment]
I experienced the same problem after upgrading today

**Comment by FrancoisDeBellescize** [comment]
> I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`.

Yeah it fix the issue for me too

**Comment by andrewding** [comment]
> I experienced the same problem after upgrading today. For my problem it was the latest expo 45.0.1 has problems

same issue here

**Comment by andrewding** [comment]
> I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`.

fixed for me as well

**Comment by karl-park-radish** [comment]
This issue is fixed at `react-native-pager-view v5.4.21`

**Comment by luckykenlin** [comment]
> 

I am facing the same problem, did you find a solution?

**Comment by luckykenlin** [comment]
> I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`.

it doesn't work for me, I have a downgrade to `v5.4.11.`,

it happens  when i using expo 45.0.1

**Comment by KrisLau** [comment]
@luckykenlin Not sure maybe you still have the wrong version. `yarn list react-native-pager-view --pattern` to check the version you actually have installed. My package.json entry:
```
"react-native-pager-view": "5.4.11",
```

you can also try `react-native start --reset-cache` and deleting node_modules and reinstalling all the modules

**Comment by robbertrosario** [comment]
> @luckykenlin Not sure maybe you still have the wrong version. `yarn list react-native-pager-view --pattern` to check the version you actually have installed. My package.json entry:
> 
> ```
> "react-native-pager-view": "5.4.11",
> ```
> 
> you can also try `react-native start --reset-cache` and deleting node_modules and reinstalling all the modules

Isn't this because expo 45.0.1 comes with react-native-pager-view 5.4.15? https://github.com/expo/expo/blob/main/CHANGELOG.md#4500--2022-04-25 or am I missing understanding how the 3rd party packages work in Expo?

**Comment by wqcstrong** [comment]
> I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`

who can give me a direction to downgrade the `react-native-pager-view` version? I have tried `expo install react-native-pager-view@5.4.11` but log the following message:

```zsh
Installing 1 SDK 45.0.0 compatible native module using Yarn.
> yarn add react-native-pager-view@5.4.15
yarn add v1.22.10
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ react-native-pager-view@5.4.15
info All dependencies
└─ react-native-pager-view@5.4.15
✨  Done in 7.98s.
```

I have no idea about that as a expo newbee, hope answers, Thx!

**Comment by andrewding** [comment]
> > I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`
> 
> who can give me a direction to downgrade the `react-native-pager-view` version? I have tried `expo install react-native-pager-view@5.4.11` but log the following message:
> 
> ```shell
> $ expo --version
> 5.4.9
> 
> $ expo install react-native-pager-view@5.4.11
> Installing 1 SDK 45.0.0 compatible native module using Yarn.
> > yarn add react-native-pager-view@5.4.15
> yarn add v1.22.10
> [1/4] 🔍  Resolving packages...
> [2/4] 🚚  Fetching packages...
> [3/4] 🔗  Linking dependencies...
> [4/4] 🔨  Building fresh packages...
> success Saved lockfile.
> success Saved 1 new dependency.
> info Direct dependencies
> └─ react-native-pager-view@5.4.15
> info All dependencies
> └─ react-native-pager-view@5.4.15
> ✨  Done in 7.98s.
> ```
> 
> I have no idea about that as a expo newbee, hope answers, Thx!

use yarn add react-native-pager-view@5.4.11 instead, bascially expo install will use the recommended package version, but in this case need to skip.

**Comment by wqcstrong** [comment]
> > > I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`
> > 
> > 
> > who can give me a direction to downgrade the `react-native-pager-view` version? I have tried `expo install react-native-pager-view@5.4.11` but log the following message:
> > ```shell
> > $ expo --version
> > 5.4.9
> > 
> > $ expo install react-native-pager-view@5.4.11
> > Installing 1 SDK 45.0.0 compatible native module using Yarn.
> > > yarn add react-native-pager-view@5.4.15
> > yarn add v1.22.10
> > [1/4] 🔍  Resolving packages...
> > [2/4] 🚚  Fetching packages...
> > [3/4] 🔗  Linking dependencies...
> > [4/4] 🔨  Building fresh packages...
> > success Saved lockfile.
> > success Saved 1 new dependency.
> > info Direct dependencies
> > └─ react-native-pager-view@5.4.15
> > info All dependencies
> > └─ react-native-pager-view@5.4.15
> > ✨  Done in 7.98s.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have no idea about that as a expo newbee, hope answers, Thx!
> 
> use yarn add react-native-pager-view@5.4.11 instead, bascially expo install will use the recommended package version, but in this case need to skip.

Downgrade the `react-native-pager-view` version doesn't work for me...

| Package | Version |
|  ----  | ----  |
| expo | 45.0.5 |
| react-native | 0.68.2 |
| react | 17.0.2 |
| react-native-tab-view | 3.1.1 |
| react-native-pager-view | 5.4.11 |
| node | 16.13.2 |
| yarn | 1.22.10 |

**Comment by wqcstrong** [comment]
Hey, guys~ I reproduct the issue.

If the `TabView` be in the `NavigationContainer` which exported from `@react-navigation/native`, the bottom blank will be there. See [Snack Expo Dev Reproduction](https://snack.expo.dev/@blucas/bottom-blank)

But I don't know the issue should be pager-view or `@react-navigation/native`, can anyone help?

**Comment by wqcstrong** [comment]
The issue should be for `react-native-pager-view`, and I report a [new issue](https://github.com/callstack/react-native-pager-view/issues/575) in there

**Comment by wqcstrong** [comment]
The issue should be for `react-native-pager-view`, and I report a [new issue](https://github.com/callstack/react-native-pager-view/issues/575) in there

**Comment by andrewding** [comment]
> The issue should be for `react-native-pager-view`, and I report a [new issue](https://github.com/callstack/react-native-pager-view/issues/575) in there

I think the issue is fixed on 5.4.21, however, expo is not using that version yet.

**Comment by wqcstrong** [comment]
> > The issue should be for `react-native-pager-view`, and I report a [new issue](https://github.com/callstack/react-native-pager-view/issues/575) in there
> 
> I think the issue is fixed on 5.4.21, however, expo is not using that version yet.

I try to toggle the vesion in the [snack reproduction](https://snack.expo.dev/@blucas/bottom-blank) to `5.4.21` / `5.4.24` and the issue is still be there, what I missed?

**Comment by andrewding** [comment]
> 

for me, when i use expo app, still same issue, but if you do a production build, the issue will disappear. Looks like expo have a "Lock down" version when using the expo app.

**Comment by ramiel1999** [comment]
The issue is still there with 5.4.24. I am not using expo go. I am using a custom development client and there is still a blank bottom on first view

**Comment by robbertrosario** [comment]
> > 
> 
> for me, when i use expo app, still same issue, but if you do a production build, the issue will disappear. Looks like expo have a "Lock down" version when using the expo app.

I'm using a production build, with 5.4.21 and Expo - and the issue is still there. I don't think it's fixed at all.

**Comment by wqcstrong** [comment]
here is my temporary solution, just looke okay:

```diff
<TabView
  navigationState={{ index, routes }}
  onIndexChange={setIndex}
  initialLayout={{ width: layout.width }}
+ sceneContainerStyle={{ overflow: 'visible' }}
  ....
/>
```

**Comment by luckykenlin** [comment]
@wqcstrong 

```
<TabView
  navigationState={{ index, routes }}
  onIndexChange={setIndex}
  initialLayout={{ width: layout.width }}
+ sceneContainerStyle={{ overflow: 'visible' }}
  ....
/>
```
thanks
this works for me

**Comment by himrocks33** [comment]
@wqcstrong Thank you! I've been researching issue for hours this fixes the issue for now!

**Comment by andrewding** [comment]
@wqcstrong <https://github.com/wqcstrong> Thank you, this works for me as
well.

**Comment by stesvis** [comment]
> here is my temporary solution, just looke okay:
> 
> ```diff
> <TabView
>   navigationState={{ index, routes }}
>   onIndexChange={setIndex}
>   initialLayout={{ width: layout.width }}
> + sceneContainerStyle={{ overflow: 'visible' }}
>   ....
> />
> ```

Is this possible on Expo somehow?

**Comment by VadymBatryn** [comment]
> I was having the same problem but downgrading `react-native-pager-view` to `v5.4.11` fixed my issue. Before I was using `v5.4.15`.

Thanks, it fixes the issue for me :)

**Comment by VadymBatryn** [comment]
Update react-native-pager-view from 5.4.15 to 5.4.25 helped me.

**Comment by okwasniewski** [comment]
Closing this since, this issue is fixed after upgrading `react-native-pager-view` to `5.4.25`.

**Comment by khoatbd55** [comment]
@wqcstrong thanks.it works for me
